version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - attach_workspace:
          at: ~/application
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          paths:
            - node_modules
          root: .
    working_directory: ~/application
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - attach_workspace:
          at: ~/application
      - run: yarn test
    working_directory: ~/application
  deploy:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  life-cycle:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
            - test
  version: 2
