version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - attach_workspace:
          at: ~/application
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          paths:
            - node_modules
          root: .
    working_directory: ~/application
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - attach_workspace:
          at: ~/application
      - run: yarn test
    working_directory: ~/application
workflows:
  life-cycle:
    jobs:
      - build
      - test:
          requires:
            - build
  version: 2
