---

- hosts: all
  connection: local
  tasks:
    - include_role:
        name: mako-ai.messenger-bot-test-pipeline
      vars:
        graph_page_about: Find your next apartment
        graph_page_name: Mako AI
        graph_subscription_callback_url: https://{{ ansible_env.HEROKU_APP_NAME }}.herokuapp.com/facebook/receive
        heroku_app_name: "{{ ansible_env.HEROKU_APP_NAME }}"
